export enum TestID {
  ACTION_BUTTON = 'action-button',
  CLEAR_ALL_DATA = 'clear-all-data',
  TRASH = 'Trash',
  BOARD = 'Board',
  CATEGORY_COLLAPSE_BUTTON = 'category-collapse-button',
  ADD_CATEGORY_BUTTON = 'add-category-button',
  OPTIONS_BUTTON = 'options-for-task',
  CORRECT_CITY = 'correct-city',
  INPUT = 'input',
  INPUT_TO_UPDATE = 'input-to-update',
  INPUT_IN_OPTIONS = 'input-in-options',
  SAVE_EDITED_VALUE = 'save-edited-val',
  ADD_NEW_TASK = 'add-new-task',
  DISABLE_TASK = 'disable-task',
  DELETE_TASK = 'delete-task',
  COLUMN_OPTIONS = 'column-options',
  CLEAR_COLUMN = 'clear-column',
  DISABLE_COLUMN_DRAG = 'disable-column-drag',
  PROHIBIT_DROP_TASKS_TO_COLUMN = 'prohibit-drop-tasks',
  RENAME_COLUMN = 'rename-column',
  EXPIRE_DATE = 'set-expire-date',
  IMPORTANT = 'important',
}
