export enum LabelText {
  CREATE_NEW_TASK = 'Create new task',
  ADD_TASK = 'Add task',
  CLEAR_ALL_DATA = 'Clear All Data',
  TRASH = 'Trash',
  MOVE_TO_BOARD = 'Back to board',
  RESTORE_FROM_TRASH = 'Restore from trash',
  SETTINGS = 'Settings',
  BOARD = 'Board',
  WELCOME_TO_CANBAN_BOARD = 'Welcome to Canban Board!',
  RENAME = 'Rename task',
  COLLAPSE_CATEGORY = 'Collapse Category List',
  ADD_CATEGORY = 'Add category',
  TASK_OPTIONS = 'open task options',
  CORRECT_CITY = 'your current location is ',
  INCORRECT_CITY = 'your current location is not ',
  YES = 'yes',
  NO = 'no',
  SAVE_EDITED_VALUE = 'save edited task content',
  COLUMN_OPTIONS = 'column-options',
  CLEAR_COLUMN = 'clear-column',
  DISABLE_COLUMN_DRAG = 'disable-column-drag',
  RENAME_COLUMN = 'rename-column',
}
